### PR TITLE
Fixes checkmarks for contactids with dashes

### LINKED ISSUE #457: Contacts are not checked as completed for certain types
A user reports that Governors and State Rep contacts don't change their icons to checkmarks when you've completed calls in the app. House and Senate seem to work fine though.

### PR DESCRIPTION
**Pull request by nickoneill**
Fixes #457

We were assuming all contactIDs had no dashes. We were wrong. Splits before the last appearing dash to get the contactid now, added some tests.

### CODE REVIEW

File: FiveCalls/FiveCallsTests/AppStateTests.swift [hunk 1]
```diff
@@ -0,0 +1,76 @@
+import XCTest
+@testable import FiveCalls
+
+final class AppStateTests: XCTestCase {
+    
+    var sut: AppState!
```
Comment (cselin) [inline FiveCalls/FiveCallsTests/AppStateTests.swift:6]: _nit:_ what is "sut"?

**Review by cselin — APPROVED** [review]
Great tests!

File: FiveCalls/FiveCallsTests/AppStateTests.swift (hunk 1 above)
Comment (nickoneill) [reply FiveCalls/FiveCallsTests/AppStateTests.swift:6]: **s**tate **u**sed for **t**est? 😂 I have no clue, I asked Claude to generate a test harness for the app state.

Comment (cselin) [reply FiveCalls/FiveCallsTests/AppStateTests.swift:6]: Haha, well that's exciting!
